[build-system]
requires = ["setuptools==83.0.0", "wheel==0.47.0"]
build-backend = "setuptools.build_meta"

[project]
name = "repo"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi==0.135.2",
    "ghapi==1.0.13",
    "prompt-toolkit==3.0.52",
]

[project.optional-dependencies]
dev = [
    "pylint==4.0.5",
    "pytest==9.0.2",
    "pytest-cov==7.1.0",
]

[project.scripts]
repo = "repo.cli.main:main"
